---
- name: install and launch metricbeats
  hosts: webservers
  become: yes
  tasks:

  - name: download metricbeat deb
    command: curl -L -O https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

  - name: install the metricbeat deb
    command: dpkg -i metricbeat-7.4.0-amd64.deb

  - name: update and drop in metricbeat.yml
    copy:
      src: /etc/ansible/files/metricbeat-config.yml
      dest: /etc/metricbeat/metricbeat.yml

  - name: enable and configure docker module
    command: metricbeat modules enable docker

  - name: setup metricbeat
    command: metricbeat setup

  - name: redirect output to standard error
    command: service metricbeat start

  - name: enable metricbeat service on boot
    systemd:
      name: metricbeat
      enabled: yes